---
# tasks file for worker-node

- name: Configuring Yum repo for k8s
  yum_repository:
    name: kubernetes
    description: Yum for k8s
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: installation of kubeadm viz kubectl & kubelet, docker and tc
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "kubeadm"
    - "docker"
    - "iproute-tc"

- name: enabling services for docker and kubelet
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - kubelet
    - docker

- name: updating systemd driver
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json

- name: restarting docker services
  service:
    name: docker
    state: restarted

- name: updating k8s config file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    src: k8s.conf

- name: restarting sysctl
  command: sysctl --system

